### PR TITLE
Update FI translations, fix typos

### PR DESCRIPTION
**Pull request by raketti**
Some improvements to the translations regarding the UI look and feel, few typos fixed.

### CODE REVIEW

**Comment by wdehoog** [comment]
How can we update the one from Transifex. Any ideas?

**Comment by raketti** [comment]
I can take a look at it on the weekend and see if I can make some sense out of it.

**Comment by wdehoog** [comment]
My idea would be download the file from transifex as a backup and then upload your file from your project. Hopefully Transifex will merge all your edits. If not and you lose translations then re-upload the backup.

**Comment by raketti** [comment]
I was able to upload my TS file to transifex, needed to translate a few strings, but everything went better than expected. I'll maintain the translations in transifex in the future.

**Pull request merged**
