### PR TITLE
finished chinese translation for hutspot

### PR DESCRIPTION
**Pull request by dashinfantry**

### CODE REVIEW

**Comment by wdehoog** [comment]
Thanks a lot. 

A few minutes ago I merged some commits with new strings. What do you think should I merge this pull request or do you want to update it first?
See for example https://github.com/sailfish-spotify/hutspot/commit/66a72d328792a9d59246c07185af732e77a65a9a#diff-3deff7af0b624641e8378a6a52f2cc3a

**Comment by dashinfantry** [comment]
Please merge my request ，thanks!

**Comment by dashinfantry** [comment]
Dose it means I should translate it from scratch ?I think a transifex  page will making  translation easier .

**Comment by wdehoog** [comment]
no not from scratch. Sorry I don't know anything about transifex.

**Comment by wdehoog** [comment]
@dashinfantry it look like the file is useless. all translated strings are in the type attribute:
```
        <translation type="æ­·å²"></translation>
```
while it should have been
```
        <translation>æ­·å²</translation>
```

**Comment by wdehoog** [comment]
@dashinfantry I'll do some vim search and replace

**Comment by wdehoog** [comment]
@dashinfantry I setup a transifex project: https://www.transifex.com/sailfish-spotify/hutspot/dashboard/
But now what? 

- Do I have to upload hutspot.ts everytime it has changed?
- Do I have to invite you or can you just join?

Sorry but this is all new to me.

**Comment by dashinfantry** [comment]
You need update it everytime it has changed and you need accept me to join your translation  team after  I apply for it.

**Pull request merged**
