### PR TITLE
add german translation

### PR DESCRIPTION
**Pull request by liquidsky**
I made a first german translation. For a few strings, I can't made a german translation because I don't know there specific meaning and dont find them in the app.

### CODE REVIEW

**Comment by wdehoog** [comment]
Thanks!

**Comment by wdehoog** [comment]
I also added it to Transifex. https://www.transifex.com/sailfish-spotify/hutspot/languages/

**Comment by liquidsky** [comment]
Don't know there is a project at transifex. I send you a request on transifex to join the team.

**Comment by wdehoog** [comment]
Using Transifex is new to me and I still don't know if I like it. Seems double work.

I did not see any notification but Transifex seems to have added you to the German translation so all is well I assume.

**Pull request merged**
