### PR TITLE
discover and register connect devices

### PR DESCRIPTION
**Pull request by wdehoog**

### CODE REVIEW

**Comment by ksiazkowicz** [comment]
Librespot running on my devices keeps appearing as inactive and disappearing from the devices list. Any ideas?

**Comment by wdehoog** [comment]
No sorry. Can you capture a log? For me the devices never showed up and now they do.

**Comment by wdehoog** [comment]
Two more things. 

This version does not register connect devices automatically but it does try to register Librespot on the phone if it does not appear in the list.

There are two device lists. One with the devices returned by the web-api and one with the devices that are discovered through mdns. Maybe refreshing and merging these list goes wrong.

**Comment by wdehoog** [comment]
I just commited a change. Now discovery is off by default and must be enabled in Settings. Hopefully your lists are now 'stable'.

**Pull request merged**
